# Generated by Django 2.0.3 on 2018-10-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gndu', '0002_posts_author_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='mobile No.'),
        ),
    ]
