# Generated by Django 2.1 on 2018-10-20 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gndu', '0003_auto_20181006_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('startdate', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.CharField(max_length=24)),
                ('client', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
    ]
